# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robzz/tek2/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robzz/tek2/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robzz/tek2/cpp_indie_studio/CMakeFiles /home/robzz/tek2/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robzz/tek2/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

srcs/Client/AI/AI.o: srcs/Client/AI/AI.cpp.o

.PHONY : srcs/Client/AI/AI.o

# target to build an object file
srcs/Client/AI/AI.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/AI/AI.cpp.o
.PHONY : srcs/Client/AI/AI.cpp.o

srcs/Client/AI/AI.i: srcs/Client/AI/AI.cpp.i

.PHONY : srcs/Client/AI/AI.i

# target to preprocess a source file
srcs/Client/AI/AI.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/AI/AI.cpp.i
.PHONY : srcs/Client/AI/AI.cpp.i

srcs/Client/AI/AI.s: srcs/Client/AI/AI.cpp.s

.PHONY : srcs/Client/AI/AI.s

# target to generate assembly for a file
srcs/Client/AI/AI.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/AI/AI.cpp.s
.PHONY : srcs/Client/AI/AI.cpp.s

srcs/Client/Bombs/Bombs.o: srcs/Client/Bombs/Bombs.cpp.o

.PHONY : srcs/Client/Bombs/Bombs.o

# target to build an object file
srcs/Client/Bombs/Bombs.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Bombs/Bombs.cpp.o
.PHONY : srcs/Client/Bombs/Bombs.cpp.o

srcs/Client/Bombs/Bombs.i: srcs/Client/Bombs/Bombs.cpp.i

.PHONY : srcs/Client/Bombs/Bombs.i

# target to preprocess a source file
srcs/Client/Bombs/Bombs.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Bombs/Bombs.cpp.i
.PHONY : srcs/Client/Bombs/Bombs.cpp.i

srcs/Client/Bombs/Bombs.s: srcs/Client/Bombs/Bombs.cpp.s

.PHONY : srcs/Client/Bombs/Bombs.s

# target to generate assembly for a file
srcs/Client/Bombs/Bombs.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Bombs/Bombs.cpp.s
.PHONY : srcs/Client/Bombs/Bombs.cpp.s

srcs/Client/Chat/Chat.o: srcs/Client/Chat/Chat.cpp.o

.PHONY : srcs/Client/Chat/Chat.o

# target to build an object file
srcs/Client/Chat/Chat.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Chat/Chat.cpp.o
.PHONY : srcs/Client/Chat/Chat.cpp.o

srcs/Client/Chat/Chat.i: srcs/Client/Chat/Chat.cpp.i

.PHONY : srcs/Client/Chat/Chat.i

# target to preprocess a source file
srcs/Client/Chat/Chat.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Chat/Chat.cpp.i
.PHONY : srcs/Client/Chat/Chat.cpp.i

srcs/Client/Chat/Chat.s: srcs/Client/Chat/Chat.cpp.s

.PHONY : srcs/Client/Chat/Chat.s

# target to generate assembly for a file
srcs/Client/Chat/Chat.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Chat/Chat.cpp.s
.PHONY : srcs/Client/Chat/Chat.cpp.s

srcs/Client/Connection/ConnectionWithServer.o: srcs/Client/Connection/ConnectionWithServer.cpp.o

.PHONY : srcs/Client/Connection/ConnectionWithServer.o

# target to build an object file
srcs/Client/Connection/ConnectionWithServer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Connection/ConnectionWithServer.cpp.o
.PHONY : srcs/Client/Connection/ConnectionWithServer.cpp.o

srcs/Client/Connection/ConnectionWithServer.i: srcs/Client/Connection/ConnectionWithServer.cpp.i

.PHONY : srcs/Client/Connection/ConnectionWithServer.i

# target to preprocess a source file
srcs/Client/Connection/ConnectionWithServer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Connection/ConnectionWithServer.cpp.i
.PHONY : srcs/Client/Connection/ConnectionWithServer.cpp.i

srcs/Client/Connection/ConnectionWithServer.s: srcs/Client/Connection/ConnectionWithServer.cpp.s

.PHONY : srcs/Client/Connection/ConnectionWithServer.s

# target to generate assembly for a file
srcs/Client/Connection/ConnectionWithServer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Connection/ConnectionWithServer.cpp.s
.PHONY : srcs/Client/Connection/ConnectionWithServer.cpp.s

srcs/Client/Core/Core.o: srcs/Client/Core/Core.cpp.o

.PHONY : srcs/Client/Core/Core.o

# target to build an object file
srcs/Client/Core/Core.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Core/Core.cpp.o
.PHONY : srcs/Client/Core/Core.cpp.o

srcs/Client/Core/Core.i: srcs/Client/Core/Core.cpp.i

.PHONY : srcs/Client/Core/Core.i

# target to preprocess a source file
srcs/Client/Core/Core.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Core/Core.cpp.i
.PHONY : srcs/Client/Core/Core.cpp.i

srcs/Client/Core/Core.s: srcs/Client/Core/Core.cpp.s

.PHONY : srcs/Client/Core/Core.s

# target to generate assembly for a file
srcs/Client/Core/Core.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Core/Core.cpp.s
.PHONY : srcs/Client/Core/Core.cpp.s

srcs/Client/Events/EventManager.o: srcs/Client/Events/EventManager.cpp.o

.PHONY : srcs/Client/Events/EventManager.o

# target to build an object file
srcs/Client/Events/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/EventManager.cpp.o
.PHONY : srcs/Client/Events/EventManager.cpp.o

srcs/Client/Events/EventManager.i: srcs/Client/Events/EventManager.cpp.i

.PHONY : srcs/Client/Events/EventManager.i

# target to preprocess a source file
srcs/Client/Events/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/EventManager.cpp.i
.PHONY : srcs/Client/Events/EventManager.cpp.i

srcs/Client/Events/EventManager.s: srcs/Client/Events/EventManager.cpp.s

.PHONY : srcs/Client/Events/EventManager.s

# target to generate assembly for a file
srcs/Client/Events/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/EventManager.cpp.s
.PHONY : srcs/Client/Events/EventManager.cpp.s

srcs/Client/Events/Events.o: srcs/Client/Events/Events.cpp.o

.PHONY : srcs/Client/Events/Events.o

# target to build an object file
srcs/Client/Events/Events.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/Events.cpp.o
.PHONY : srcs/Client/Events/Events.cpp.o

srcs/Client/Events/Events.i: srcs/Client/Events/Events.cpp.i

.PHONY : srcs/Client/Events/Events.i

# target to preprocess a source file
srcs/Client/Events/Events.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/Events.cpp.i
.PHONY : srcs/Client/Events/Events.cpp.i

srcs/Client/Events/Events.s: srcs/Client/Events/Events.cpp.s

.PHONY : srcs/Client/Events/Events.s

# target to generate assembly for a file
srcs/Client/Events/Events.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Events/Events.cpp.s
.PHONY : srcs/Client/Events/Events.cpp.s

srcs/Client/GUI/Menu.o: srcs/Client/GUI/Menu.cpp.o

.PHONY : srcs/Client/GUI/Menu.o

# target to build an object file
srcs/Client/GUI/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/Menu.cpp.o
.PHONY : srcs/Client/GUI/Menu.cpp.o

srcs/Client/GUI/Menu.i: srcs/Client/GUI/Menu.cpp.i

.PHONY : srcs/Client/GUI/Menu.i

# target to preprocess a source file
srcs/Client/GUI/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/Menu.cpp.i
.PHONY : srcs/Client/GUI/Menu.cpp.i

srcs/Client/GUI/Menu.s: srcs/Client/GUI/Menu.cpp.s

.PHONY : srcs/Client/GUI/Menu.s

# target to generate assembly for a file
srcs/Client/GUI/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/Menu.cpp.s
.PHONY : srcs/Client/GUI/Menu.cpp.s

srcs/Client/GUI/SplashScreen.o: srcs/Client/GUI/SplashScreen.cpp.o

.PHONY : srcs/Client/GUI/SplashScreen.o

# target to build an object file
srcs/Client/GUI/SplashScreen.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/SplashScreen.cpp.o
.PHONY : srcs/Client/GUI/SplashScreen.cpp.o

srcs/Client/GUI/SplashScreen.i: srcs/Client/GUI/SplashScreen.cpp.i

.PHONY : srcs/Client/GUI/SplashScreen.i

# target to preprocess a source file
srcs/Client/GUI/SplashScreen.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/SplashScreen.cpp.i
.PHONY : srcs/Client/GUI/SplashScreen.cpp.i

srcs/Client/GUI/SplashScreen.s: srcs/Client/GUI/SplashScreen.cpp.s

.PHONY : srcs/Client/GUI/SplashScreen.s

# target to generate assembly for a file
srcs/Client/GUI/SplashScreen.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/GUI/SplashScreen.cpp.s
.PHONY : srcs/Client/GUI/SplashScreen.cpp.s

srcs/Client/Game/Game.o: srcs/Client/Game/Game.cpp.o

.PHONY : srcs/Client/Game/Game.o

# target to build an object file
srcs/Client/Game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/Game.cpp.o
.PHONY : srcs/Client/Game/Game.cpp.o

srcs/Client/Game/Game.i: srcs/Client/Game/Game.cpp.i

.PHONY : srcs/Client/Game/Game.i

# target to preprocess a source file
srcs/Client/Game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/Game.cpp.i
.PHONY : srcs/Client/Game/Game.cpp.i

srcs/Client/Game/Game.s: srcs/Client/Game/Game.cpp.s

.PHONY : srcs/Client/Game/Game.s

# target to generate assembly for a file
srcs/Client/Game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/Game.cpp.s
.PHONY : srcs/Client/Game/Game.cpp.s

srcs/Client/Game/GameInfos.o: srcs/Client/Game/GameInfos.cpp.o

.PHONY : srcs/Client/Game/GameInfos.o

# target to build an object file
srcs/Client/Game/GameInfos.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/GameInfos.cpp.o
.PHONY : srcs/Client/Game/GameInfos.cpp.o

srcs/Client/Game/GameInfos.i: srcs/Client/Game/GameInfos.cpp.i

.PHONY : srcs/Client/Game/GameInfos.i

# target to preprocess a source file
srcs/Client/Game/GameInfos.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/GameInfos.cpp.i
.PHONY : srcs/Client/Game/GameInfos.cpp.i

srcs/Client/Game/GameInfos.s: srcs/Client/Game/GameInfos.cpp.s

.PHONY : srcs/Client/Game/GameInfos.s

# target to generate assembly for a file
srcs/Client/Game/GameInfos.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/GameInfos.cpp.s
.PHONY : srcs/Client/Game/GameInfos.cpp.s

srcs/Client/Game/ManageMap.o: srcs/Client/Game/ManageMap.cpp.o

.PHONY : srcs/Client/Game/ManageMap.o

# target to build an object file
srcs/Client/Game/ManageMap.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/ManageMap.cpp.o
.PHONY : srcs/Client/Game/ManageMap.cpp.o

srcs/Client/Game/ManageMap.i: srcs/Client/Game/ManageMap.cpp.i

.PHONY : srcs/Client/Game/ManageMap.i

# target to preprocess a source file
srcs/Client/Game/ManageMap.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/ManageMap.cpp.i
.PHONY : srcs/Client/Game/ManageMap.cpp.i

srcs/Client/Game/ManageMap.s: srcs/Client/Game/ManageMap.cpp.s

.PHONY : srcs/Client/Game/ManageMap.s

# target to generate assembly for a file
srcs/Client/Game/ManageMap.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Game/ManageMap.cpp.s
.PHONY : srcs/Client/Game/ManageMap.cpp.s

srcs/Client/Graphism/Camera.o: srcs/Client/Graphism/Camera.cpp.o

.PHONY : srcs/Client/Graphism/Camera.o

# target to build an object file
srcs/Client/Graphism/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Camera.cpp.o
.PHONY : srcs/Client/Graphism/Camera.cpp.o

srcs/Client/Graphism/Camera.i: srcs/Client/Graphism/Camera.cpp.i

.PHONY : srcs/Client/Graphism/Camera.i

# target to preprocess a source file
srcs/Client/Graphism/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Camera.cpp.i
.PHONY : srcs/Client/Graphism/Camera.cpp.i

srcs/Client/Graphism/Camera.s: srcs/Client/Graphism/Camera.cpp.s

.PHONY : srcs/Client/Graphism/Camera.s

# target to generate assembly for a file
srcs/Client/Graphism/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Camera.cpp.s
.PHONY : srcs/Client/Graphism/Camera.cpp.s

srcs/Client/Graphism/Decor.o: srcs/Client/Graphism/Decor.cpp.o

.PHONY : srcs/Client/Graphism/Decor.o

# target to build an object file
srcs/Client/Graphism/Decor.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Decor.cpp.o
.PHONY : srcs/Client/Graphism/Decor.cpp.o

srcs/Client/Graphism/Decor.i: srcs/Client/Graphism/Decor.cpp.i

.PHONY : srcs/Client/Graphism/Decor.i

# target to preprocess a source file
srcs/Client/Graphism/Decor.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Decor.cpp.i
.PHONY : srcs/Client/Graphism/Decor.cpp.i

srcs/Client/Graphism/Decor.s: srcs/Client/Graphism/Decor.cpp.s

.PHONY : srcs/Client/Graphism/Decor.s

# target to generate assembly for a file
srcs/Client/Graphism/Decor.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Decor.cpp.s
.PHONY : srcs/Client/Graphism/Decor.cpp.s

srcs/Client/Graphism/Graphism.o: srcs/Client/Graphism/Graphism.cpp.o

.PHONY : srcs/Client/Graphism/Graphism.o

# target to build an object file
srcs/Client/Graphism/Graphism.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Graphism.cpp.o
.PHONY : srcs/Client/Graphism/Graphism.cpp.o

srcs/Client/Graphism/Graphism.i: srcs/Client/Graphism/Graphism.cpp.i

.PHONY : srcs/Client/Graphism/Graphism.i

# target to preprocess a source file
srcs/Client/Graphism/Graphism.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Graphism.cpp.i
.PHONY : srcs/Client/Graphism/Graphism.cpp.i

srcs/Client/Graphism/Graphism.s: srcs/Client/Graphism/Graphism.cpp.s

.PHONY : srcs/Client/Graphism/Graphism.s

# target to generate assembly for a file
srcs/Client/Graphism/Graphism.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Graphism.cpp.s
.PHONY : srcs/Client/Graphism/Graphism.cpp.s

srcs/Client/Graphism/Window.o: srcs/Client/Graphism/Window.cpp.o

.PHONY : srcs/Client/Graphism/Window.o

# target to build an object file
srcs/Client/Graphism/Window.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Window.cpp.o
.PHONY : srcs/Client/Graphism/Window.cpp.o

srcs/Client/Graphism/Window.i: srcs/Client/Graphism/Window.cpp.i

.PHONY : srcs/Client/Graphism/Window.i

# target to preprocess a source file
srcs/Client/Graphism/Window.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Window.cpp.i
.PHONY : srcs/Client/Graphism/Window.cpp.i

srcs/Client/Graphism/Window.s: srcs/Client/Graphism/Window.cpp.s

.PHONY : srcs/Client/Graphism/Window.s

# target to generate assembly for a file
srcs/Client/Graphism/Window.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Graphism/Window.cpp.s
.PHONY : srcs/Client/Graphism/Window.cpp.s

srcs/Client/Local/Backup.o: srcs/Client/Local/Backup.cpp.o

.PHONY : srcs/Client/Local/Backup.o

# target to build an object file
srcs/Client/Local/Backup.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/Backup.cpp.o
.PHONY : srcs/Client/Local/Backup.cpp.o

srcs/Client/Local/Backup.i: srcs/Client/Local/Backup.cpp.i

.PHONY : srcs/Client/Local/Backup.i

# target to preprocess a source file
srcs/Client/Local/Backup.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/Backup.cpp.i
.PHONY : srcs/Client/Local/Backup.cpp.i

srcs/Client/Local/Backup.s: srcs/Client/Local/Backup.cpp.s

.PHONY : srcs/Client/Local/Backup.s

# target to generate assembly for a file
srcs/Client/Local/Backup.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/Backup.cpp.s
.PHONY : srcs/Client/Local/Backup.cpp.s

srcs/Client/Local/LocalGame.o: srcs/Client/Local/LocalGame.cpp.o

.PHONY : srcs/Client/Local/LocalGame.o

# target to build an object file
srcs/Client/Local/LocalGame.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/LocalGame.cpp.o
.PHONY : srcs/Client/Local/LocalGame.cpp.o

srcs/Client/Local/LocalGame.i: srcs/Client/Local/LocalGame.cpp.i

.PHONY : srcs/Client/Local/LocalGame.i

# target to preprocess a source file
srcs/Client/Local/LocalGame.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/LocalGame.cpp.i
.PHONY : srcs/Client/Local/LocalGame.cpp.i

srcs/Client/Local/LocalGame.s: srcs/Client/Local/LocalGame.cpp.s

.PHONY : srcs/Client/Local/LocalGame.s

# target to generate assembly for a file
srcs/Client/Local/LocalGame.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Local/LocalGame.cpp.s
.PHONY : srcs/Client/Local/LocalGame.cpp.s

srcs/Client/Map/Map.o: srcs/Client/Map/Map.cpp.o

.PHONY : srcs/Client/Map/Map.o

# target to build an object file
srcs/Client/Map/Map.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/Map.cpp.o
.PHONY : srcs/Client/Map/Map.cpp.o

srcs/Client/Map/Map.i: srcs/Client/Map/Map.cpp.i

.PHONY : srcs/Client/Map/Map.i

# target to preprocess a source file
srcs/Client/Map/Map.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/Map.cpp.i
.PHONY : srcs/Client/Map/Map.cpp.i

srcs/Client/Map/Map.s: srcs/Client/Map/Map.cpp.s

.PHONY : srcs/Client/Map/Map.s

# target to generate assembly for a file
srcs/Client/Map/Map.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/Map.cpp.s
.PHONY : srcs/Client/Map/Map.cpp.s

srcs/Client/Map/MapEdit.o: srcs/Client/Map/MapEdit.cpp.o

.PHONY : srcs/Client/Map/MapEdit.o

# target to build an object file
srcs/Client/Map/MapEdit.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/MapEdit.cpp.o
.PHONY : srcs/Client/Map/MapEdit.cpp.o

srcs/Client/Map/MapEdit.i: srcs/Client/Map/MapEdit.cpp.i

.PHONY : srcs/Client/Map/MapEdit.i

# target to preprocess a source file
srcs/Client/Map/MapEdit.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/MapEdit.cpp.i
.PHONY : srcs/Client/Map/MapEdit.cpp.i

srcs/Client/Map/MapEdit.s: srcs/Client/Map/MapEdit.cpp.s

.PHONY : srcs/Client/Map/MapEdit.s

# target to generate assembly for a file
srcs/Client/Map/MapEdit.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Map/MapEdit.cpp.s
.PHONY : srcs/Client/Map/MapEdit.cpp.s

srcs/Client/Player/Player.o: srcs/Client/Player/Player.cpp.o

.PHONY : srcs/Client/Player/Player.o

# target to build an object file
srcs/Client/Player/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/Player.cpp.o
.PHONY : srcs/Client/Player/Player.cpp.o

srcs/Client/Player/Player.i: srcs/Client/Player/Player.cpp.i

.PHONY : srcs/Client/Player/Player.i

# target to preprocess a source file
srcs/Client/Player/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/Player.cpp.i
.PHONY : srcs/Client/Player/Player.cpp.i

srcs/Client/Player/Player.s: srcs/Client/Player/Player.cpp.s

.PHONY : srcs/Client/Player/Player.s

# target to generate assembly for a file
srcs/Client/Player/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/Player.cpp.s
.PHONY : srcs/Client/Player/Player.cpp.s

srcs/Client/Player/PlayerActions.o: srcs/Client/Player/PlayerActions.cpp.o

.PHONY : srcs/Client/Player/PlayerActions.o

# target to build an object file
srcs/Client/Player/PlayerActions.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/PlayerActions.cpp.o
.PHONY : srcs/Client/Player/PlayerActions.cpp.o

srcs/Client/Player/PlayerActions.i: srcs/Client/Player/PlayerActions.cpp.i

.PHONY : srcs/Client/Player/PlayerActions.i

# target to preprocess a source file
srcs/Client/Player/PlayerActions.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/PlayerActions.cpp.i
.PHONY : srcs/Client/Player/PlayerActions.cpp.i

srcs/Client/Player/PlayerActions.s: srcs/Client/Player/PlayerActions.cpp.s

.PHONY : srcs/Client/Player/PlayerActions.s

# target to generate assembly for a file
srcs/Client/Player/PlayerActions.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/Player/PlayerActions.cpp.s
.PHONY : srcs/Client/Player/PlayerActions.cpp.s

srcs/Client/main.o: srcs/Client/main.cpp.o

.PHONY : srcs/Client/main.o

# target to build an object file
srcs/Client/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/main.cpp.o
.PHONY : srcs/Client/main.cpp.o

srcs/Client/main.i: srcs/Client/main.cpp.i

.PHONY : srcs/Client/main.i

# target to preprocess a source file
srcs/Client/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/main.cpp.i
.PHONY : srcs/Client/main.cpp.i

srcs/Client/main.s: srcs/Client/main.cpp.s

.PHONY : srcs/Client/main.s

# target to generate assembly for a file
srcs/Client/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Client/main.cpp.s
.PHONY : srcs/Client/main.cpp.s

srcs/Server/LaunchServer.o: srcs/Server/LaunchServer.cpp.o

.PHONY : srcs/Server/LaunchServer.o

# target to build an object file
srcs/Server/LaunchServer.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Server/LaunchServer.cpp.o
.PHONY : srcs/Server/LaunchServer.cpp.o

srcs/Server/LaunchServer.i: srcs/Server/LaunchServer.cpp.i

.PHONY : srcs/Server/LaunchServer.i

# target to preprocess a source file
srcs/Server/LaunchServer.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Server/LaunchServer.cpp.i
.PHONY : srcs/Server/LaunchServer.cpp.i

srcs/Server/LaunchServer.s: srcs/Server/LaunchServer.cpp.s

.PHONY : srcs/Server/LaunchServer.s

# target to generate assembly for a file
srcs/Server/LaunchServer.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Server/LaunchServer.cpp.s
.PHONY : srcs/Server/LaunchServer.cpp.s

srcs/Shared/AI/AI.o: srcs/Shared/AI/AI.cpp.o

.PHONY : srcs/Shared/AI/AI.o

# target to build an object file
srcs/Shared/AI/AI.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/AI.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/AI.cpp.o
.PHONY : srcs/Shared/AI/AI.cpp.o

srcs/Shared/AI/AI.i: srcs/Shared/AI/AI.cpp.i

.PHONY : srcs/Shared/AI/AI.i

# target to preprocess a source file
srcs/Shared/AI/AI.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/AI.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/AI.cpp.i
.PHONY : srcs/Shared/AI/AI.cpp.i

srcs/Shared/AI/AI.s: srcs/Shared/AI/AI.cpp.s

.PHONY : srcs/Shared/AI/AI.s

# target to generate assembly for a file
srcs/Shared/AI/AI.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/AI.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/AI.cpp.s
.PHONY : srcs/Shared/AI/AI.cpp.s

srcs/Shared/AI/Astar.o: srcs/Shared/AI/Astar.cpp.o

.PHONY : srcs/Shared/AI/Astar.o

# target to build an object file
srcs/Shared/AI/Astar.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/Astar.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/Astar.cpp.o
.PHONY : srcs/Shared/AI/Astar.cpp.o

srcs/Shared/AI/Astar.i: srcs/Shared/AI/Astar.cpp.i

.PHONY : srcs/Shared/AI/Astar.i

# target to preprocess a source file
srcs/Shared/AI/Astar.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/Astar.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/Astar.cpp.i
.PHONY : srcs/Shared/AI/Astar.cpp.i

srcs/Shared/AI/Astar.s: srcs/Shared/AI/Astar.cpp.s

.PHONY : srcs/Shared/AI/Astar.s

# target to generate assembly for a file
srcs/Shared/AI/Astar.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/AI/Astar.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/AI/Astar.cpp.s
.PHONY : srcs/Shared/AI/Astar.cpp.s

srcs/Shared/Clock.o: srcs/Shared/Clock.cpp.o

.PHONY : srcs/Shared/Clock.o

# target to build an object file
srcs/Shared/Clock.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Clock.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Clock.cpp.o
.PHONY : srcs/Shared/Clock.cpp.o

srcs/Shared/Clock.i: srcs/Shared/Clock.cpp.i

.PHONY : srcs/Shared/Clock.i

# target to preprocess a source file
srcs/Shared/Clock.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Clock.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Clock.cpp.i
.PHONY : srcs/Shared/Clock.cpp.i

srcs/Shared/Clock.s: srcs/Shared/Clock.cpp.s

.PHONY : srcs/Shared/Clock.s

# target to generate assembly for a file
srcs/Shared/Clock.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Clock.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Clock.cpp.s
.PHONY : srcs/Shared/Clock.cpp.s

srcs/Shared/ManageStrings.o: srcs/Shared/ManageStrings.cpp.o

.PHONY : srcs/Shared/ManageStrings.o

# target to build an object file
srcs/Shared/ManageStrings.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/ManageStrings.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/ManageStrings.cpp.o
.PHONY : srcs/Shared/ManageStrings.cpp.o

srcs/Shared/ManageStrings.i: srcs/Shared/ManageStrings.cpp.i

.PHONY : srcs/Shared/ManageStrings.i

# target to preprocess a source file
srcs/Shared/ManageStrings.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/ManageStrings.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/ManageStrings.cpp.i
.PHONY : srcs/Shared/ManageStrings.cpp.i

srcs/Shared/ManageStrings.s: srcs/Shared/ManageStrings.cpp.s

.PHONY : srcs/Shared/ManageStrings.s

# target to generate assembly for a file
srcs/Shared/ManageStrings.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/ManageStrings.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/ManageStrings.cpp.s
.PHONY : srcs/Shared/ManageStrings.cpp.s

srcs/Shared/Server.o: srcs/Shared/Server.cpp.o

.PHONY : srcs/Shared/Server.o

# target to build an object file
srcs/Shared/Server.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Server.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Server.cpp.o
.PHONY : srcs/Shared/Server.cpp.o

srcs/Shared/Server.i: srcs/Shared/Server.cpp.i

.PHONY : srcs/Shared/Server.i

# target to preprocess a source file
srcs/Shared/Server.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Server.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Server.cpp.i
.PHONY : srcs/Shared/Server.cpp.i

srcs/Shared/Server.s: srcs/Shared/Server.cpp.s

.PHONY : srcs/Shared/Server.s

# target to generate assembly for a file
srcs/Shared/Server.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Server.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Server.cpp.s
.PHONY : srcs/Shared/Server.cpp.s

srcs/Shared/Socket.o: srcs/Shared/Socket.cpp.o

.PHONY : srcs/Shared/Socket.o

# target to build an object file
srcs/Shared/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Socket.cpp.o
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Socket.cpp.o
.PHONY : srcs/Shared/Socket.cpp.o

srcs/Shared/Socket.i: srcs/Shared/Socket.cpp.i

.PHONY : srcs/Shared/Socket.i

# target to preprocess a source file
srcs/Shared/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Socket.cpp.i
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Socket.cpp.i
.PHONY : srcs/Shared/Socket.cpp.i

srcs/Shared/Socket.s: srcs/Shared/Socket.cpp.s

.PHONY : srcs/Shared/Socket.s

# target to generate assembly for a file
srcs/Shared/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Shared/Socket.cpp.s
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/srcs/Shared/Socket.cpp.s
.PHONY : srcs/Shared/Socket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... server"
	@echo "... bomberman"
	@echo "... srcs/Client/AI/AI.o"
	@echo "... srcs/Client/AI/AI.i"
	@echo "... srcs/Client/AI/AI.s"
	@echo "... srcs/Client/Bombs/Bombs.o"
	@echo "... srcs/Client/Bombs/Bombs.i"
	@echo "... srcs/Client/Bombs/Bombs.s"
	@echo "... srcs/Client/Chat/Chat.o"
	@echo "... srcs/Client/Chat/Chat.i"
	@echo "... srcs/Client/Chat/Chat.s"
	@echo "... srcs/Client/Connection/ConnectionWithServer.o"
	@echo "... srcs/Client/Connection/ConnectionWithServer.i"
	@echo "... srcs/Client/Connection/ConnectionWithServer.s"
	@echo "... srcs/Client/Core/Core.o"
	@echo "... srcs/Client/Core/Core.i"
	@echo "... srcs/Client/Core/Core.s"
	@echo "... srcs/Client/Events/EventManager.o"
	@echo "... srcs/Client/Events/EventManager.i"
	@echo "... srcs/Client/Events/EventManager.s"
	@echo "... srcs/Client/Events/Events.o"
	@echo "... srcs/Client/Events/Events.i"
	@echo "... srcs/Client/Events/Events.s"
	@echo "... srcs/Client/GUI/Menu.o"
	@echo "... srcs/Client/GUI/Menu.i"
	@echo "... srcs/Client/GUI/Menu.s"
	@echo "... srcs/Client/GUI/SplashScreen.o"
	@echo "... srcs/Client/GUI/SplashScreen.i"
	@echo "... srcs/Client/GUI/SplashScreen.s"
	@echo "... srcs/Client/Game/Game.o"
	@echo "... srcs/Client/Game/Game.i"
	@echo "... srcs/Client/Game/Game.s"
	@echo "... srcs/Client/Game/GameInfos.o"
	@echo "... srcs/Client/Game/GameInfos.i"
	@echo "... srcs/Client/Game/GameInfos.s"
	@echo "... srcs/Client/Game/ManageMap.o"
	@echo "... srcs/Client/Game/ManageMap.i"
	@echo "... srcs/Client/Game/ManageMap.s"
	@echo "... srcs/Client/Graphism/Camera.o"
	@echo "... srcs/Client/Graphism/Camera.i"
	@echo "... srcs/Client/Graphism/Camera.s"
	@echo "... srcs/Client/Graphism/Decor.o"
	@echo "... srcs/Client/Graphism/Decor.i"
	@echo "... srcs/Client/Graphism/Decor.s"
	@echo "... srcs/Client/Graphism/Graphism.o"
	@echo "... srcs/Client/Graphism/Graphism.i"
	@echo "... srcs/Client/Graphism/Graphism.s"
	@echo "... srcs/Client/Graphism/Window.o"
	@echo "... srcs/Client/Graphism/Window.i"
	@echo "... srcs/Client/Graphism/Window.s"
	@echo "... srcs/Client/Local/Backup.o"
	@echo "... srcs/Client/Local/Backup.i"
	@echo "... srcs/Client/Local/Backup.s"
	@echo "... srcs/Client/Local/LocalGame.o"
	@echo "... srcs/Client/Local/LocalGame.i"
	@echo "... srcs/Client/Local/LocalGame.s"
	@echo "... srcs/Client/Map/Map.o"
	@echo "... srcs/Client/Map/Map.i"
	@echo "... srcs/Client/Map/Map.s"
	@echo "... srcs/Client/Map/MapEdit.o"
	@echo "... srcs/Client/Map/MapEdit.i"
	@echo "... srcs/Client/Map/MapEdit.s"
	@echo "... srcs/Client/Player/Player.o"
	@echo "... srcs/Client/Player/Player.i"
	@echo "... srcs/Client/Player/Player.s"
	@echo "... srcs/Client/Player/PlayerActions.o"
	@echo "... srcs/Client/Player/PlayerActions.i"
	@echo "... srcs/Client/Player/PlayerActions.s"
	@echo "... srcs/Client/main.o"
	@echo "... srcs/Client/main.i"
	@echo "... srcs/Client/main.s"
	@echo "... srcs/Server/LaunchServer.o"
	@echo "... srcs/Server/LaunchServer.i"
	@echo "... srcs/Server/LaunchServer.s"
	@echo "... srcs/Shared/AI/AI.o"
	@echo "... srcs/Shared/AI/AI.i"
	@echo "... srcs/Shared/AI/AI.s"
	@echo "... srcs/Shared/AI/Astar.o"
	@echo "... srcs/Shared/AI/Astar.i"
	@echo "... srcs/Shared/AI/Astar.s"
	@echo "... srcs/Shared/Clock.o"
	@echo "... srcs/Shared/Clock.i"
	@echo "... srcs/Shared/Clock.s"
	@echo "... srcs/Shared/ManageStrings.o"
	@echo "... srcs/Shared/ManageStrings.i"
	@echo "... srcs/Shared/ManageStrings.s"
	@echo "... srcs/Shared/Server.o"
	@echo "... srcs/Shared/Server.i"
	@echo "... srcs/Shared/Server.s"
	@echo "... srcs/Shared/Socket.o"
	@echo "... srcs/Shared/Socket.i"
	@echo "... srcs/Shared/Socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

